# Generated by Django 5.2.7 on 2025-10-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='storage/images')),
                ('lab_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='storage.labs')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_image', models.ImageField(blank=True, default='', null=True, upload_to='storage/images')),
                ('maintenance_date', models.DateField(auto_now_add=True)),
                ('machinary_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
                ('maintenance_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.suplier')),
            ],
        ),
    ]
