# Generated by Django 5.2.7 on 2025-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='upcoming_maitenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
