# Generated by Django 5.2.7 on 2025-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_maintenance_upcoming_maitenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(),
        ),
    ]
