# Generated by Django 5.2.7 on 2025-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storage_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='serial',
            field=models.CharField(default='', max_length=50),
        ),
    ]
