# Generated by Django 5.2.7 on 2025-10-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_storage_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_neccesary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_image',
            field=models.ImageField(blank=True, null=True, upload_to='storage/images'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage/images'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='name_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storage',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.brand'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.types'),
        ),
    ]
