# Generated by Django 5.2.7 on 2025-10-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_brand_types_maintenance_maintenance_neccesary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='upcoming_maitenance',
            new_name='upcoming_maintenance',
        ),
        migrations.AlterField(
            model_name='storage',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='storage.brand'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
