# Generated by Django 5.2.7 on 2025-10-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_upcoming_maitenance_maintenance_upcoming_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='storage.types'),
        ),
    ]
