# Generated by Django 5.2.7 on 2025-10-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_maintenance_maintenance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_neccesary',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_file',
            field=models.FileField(null=True, upload_to='storage/files'),
        ),
        migrations.AddField(
            model_name='storage',
            name='necessary_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
