# Generated by Django 5.2.7 on 2025-10-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_maintenance_maintenance_neccesary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_file',
            field=models.FileField(blank=True, null=True, upload_to='storage/files'),
        ),
    ]
