# Generated by Django 5.2.7 on 2025-11-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_maintenance_maintenance_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
