# Generated by Django 5.2.7 on 2025-11-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_maintenance_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_image',
            field=models.ImageField(blank=True, null=True, upload_to='storage/images/maintenances'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage/images/storage'),
        ),
    ]
