# Generated by Django 5.2.8 on 2025-11-12 17:24

import storage.utils.validation_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_maintenance_maintenance_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_file',
            field=models.FileField(blank=True, null=True, upload_to='storage/files', validators=[storage.utils.validation_file.validate_pdf]),
        ),
    ]
