# Generated by Django 5.2.8 on 2025-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_maintenance_maintenance_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='email_sent_30_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='email_sent_7_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='email_sent_due',
            field=models.BooleanField(default=False),
        ),
    ]
