# Generated by Django 5.2.8 on 2025-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_maintenance_email_sent_30_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='upcoming_maintenance',
        ),
        migrations.AddField(
            model_name='storage',
            name='upcoming_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
