# Generated by Django 5.2.8 on 2025-11-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_remove_maintenance_upcoming_maintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='email_sent_30_days',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='email_sent_7_days',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='email_sent_due',
        ),
        migrations.AddField(
            model_name='storage',
            name='email_sent_30_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='email_sent_7_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='email_sent_due',
            field=models.BooleanField(default=False),
        ),
    ]
