# Generated by Django 5.2.8 on 2026-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_remove_maintenance_email_sent_30_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
