# Generated by Django 5.2.8 on 2026-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_storage_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='necessary_maintenance',
            field=models.CharField(choices=[('AD', 'Al día'), ('PV', 'Por vencer'), ('VE', 'Vencido')], default='AD', max_length=2),
        ),
    ]
