# Generated by Django 5.2.8 on 2026-02-05 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_alter_storage_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
